apiVersion: v1
kind: Secret
metadata:
  name: nyaya-secrets
  namespace: nyaya-ai
type: Opaque
# Encode: echo -n "yourvalue" | base64
data:
  NEXTAUTH_SECRET: <base64>
  GOOGLE_CLIENT_ID: <base64>
  GOOGLE_CLIENT_SECRET: <base64>
  GROQ_API_KEY: <base64>
  CLOUDINARY_CLOUD_NAME: <base64>
  CLOUDINARY_API_KEY: <base64>
  CLOUDINARY_API_SECRET: <base64>
  STRIPE_SECRET_KEY: <base64>
  STRIPE_WEBHOOK_SECRET: <base64>
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: <base64>
